# Generated by Django 3.2.12 on 2022-04-17 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GEN', '일반'), ('ACC', '계정'), ('ETC', '기타')], default='GEN', max_length=3, verbose_name='카테고리')),
                ('title', models.TextField(verbose_name='제목')),
                ('email', models.TextField(verbose_name='이메일')),
                ('email_rcv_yn', models.CharField(max_length=1, verbose_name='이메일수신여부')),
                ('phone', models.TextField(verbose_name='핸드폰번호')),
                ('phone_rcv_yn', models.CharField(max_length=1, verbose_name='문자수신여부')),
                ('question', models.TextField(verbose_name='질문내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='답변내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('final_created_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정일시')),
                ('final_writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supportss_Answers_related', to=settings.AUTH_USER_MODEL, verbose_name='최종 수정자')),
                ('ref_inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supports.inquiry', verbose_name='참조문의글')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
        ),
    ]
